config:
  credentials:
  - id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.navy_apathetic_rabbit.sh
        container: qc.acc_tangerine_fierce_ibex
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.amethyst_whimsical_manatee.sh
        container: qc.doc_banana_peppy_hawk
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.lime_hardworking_owl.sh
        container: qc.doc_rust_foolish_porpoise
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.harlequin_zealous_stingray.sh
        container: qc.doc_glaucous_romantic_reindeer
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_peaceful_mink.sh
        container: qc.lic_mulberry_respectful_ibex
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.byzantium_methodical_kangaroo.sh
        container: qc.sec_saffron_warm_ibis
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flax_amused_python.sh
        container: qc.sty_obsidian_fierce_whale
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.linen_hardworking_bear.sh
        container: qc.sty_jet_outgoing_beaver
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.pistachio_compassionate_clownfish.sh
        container: qc.sty_zinnia_articulate_lynx
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gamboge_unique_cougar.sh
        container: qc.uni_clementine_amiable_echidna
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.orange_thoughtful_frog.sh
        container: qc.ver_zinnia_protective_skunk
timeout: 5400
