config:
  credentials:
  - id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
      repo: https://gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_audacious_gecko.sh
        container: qc.acc_alabaster_gentle_elephant
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_anxious_hedgehog.sh
        container: qc.doc_viridian_apprehensive_caiman
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test git:
        commands:
        - /usr/bin/env sh .sqa/script.gray_reflective_eel.sh
        container: qc.doc_tangerine_balanced_chameleon
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.mango_focused_hamster.sh
        container: qc.doc_daffodil_logical_elk
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_sad_leopard.sh
        container: qc.lic_mulberry_determined_lionfish
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lagoon_warm_capybara.sh
        container: qc.sec_cerise_perky_hydra
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snow_delighted_condor.sh
        container: qc.sty_chili_lucky_mandrill
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clove_tenacious_groundhog.sh
        container: qc.sty_butterscotch_confident_albatross
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_dramatic_spren.sh
        container: qc.sty_boysenberry_understanding_dormouse
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.butter_wise_pangolin.sh
        container: qc.uni_obsidian_kind_tapir
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/analytical-workflowtemplates-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nutmeg_grateful_walrus.sh
        container: qc.ver_mustard_organized_macaw
timeout: 5400
